### ISSUE TITLE
Most time Crashes when switch to "All" giveaways

### ISSUE THREAD

**Issue by xXxPsymanxXx** [PrOF-kk/SteamGifts#10]
Anything Else (Group, Whitelist, Recommend, Discusson,...) works fine. I only use a Limit of <500 entries as filter, If that helps. My workaround to restart the App after the crash: Phone in Flightmode, Open the App, Switch Back to "Group" or Something Else, flightmode Off and reload the Page.

- Xiaomi Android 13 based MIUI 14 (Problem existed also on my previous Huawei Phone with Android 10 EMUI). Both 8 GB RAM.
- Region: Germany
- App Version 1.5.17 Beta (as far as i remember: Problem exists since the last official Release from Mabako)

**Thank you very much 4 keeping that App alive :-)**

Log:

java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionEmptyViewHolder{2a9c6dc position=11 id=-1, oldPos=10, pLpos:10 scrap [attachedScrap] tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{86a9c41 VFED..... ......ID 0,0-720,640 #7f09014b app:id/list}, adapter:net.mabako.steamgifts.adapters.GiveawayAdapter@82fc990, layout:androidx.recyclerview.widget.LinearLayoutManager@c4685e6, context:net.mabako.steamgifts.activities.MainActivity@267516f
	at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:6590)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6796)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4591)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:4016)
	at android.view.View.measure(View.java:26905)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26905)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onMeasure(SwipeRefreshLayout.java:641)
	at android.view.View.measure(View.java:26905)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:26905)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26905)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:833)
	at android.view.View.measure(View.java:26905)
	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1156)
	at android.view.View.measure(View.java:26905)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
	at android.view.View.measure(View.java:26905)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26905)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26905)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26905)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:840)
	at android.view.View.measure(View.java:26905)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4281)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2946)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3229)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2651)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9819)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1429)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1437)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1046)
	at android.view.Choreographer.doFrame(Choreographer.java:936)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1405)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8324)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:581)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

**Comment by PrOF-kk** [comment]
Thanks for the bug report! I finally managed to reproduce this today, it's the same problem that's causing #1, that's hopefully fixed in the next release  🎉🎉🎉

**Comment by xXxPsymanxXx** [comment]
Thanks for the quick update. Unfortunately, the BUG is still present even after a clean reinstallation to beta 2 😔. I have submitted another log from beta 2:

java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionEmptyViewHolder{bd2f65e position=23 id=-1, oldPos=22, pLpos:22 scrap [attachedScrap] tmpDetached not recyclable(1) no parent} androidx.recyclerview.widget.RecyclerView{1b7ea15 VFED..... ......ID 0,0-720,1300 #7f09014b app:id/list}, adapter:net.mabako.steamgifts.adapters.GiveawayAdapter@66e0aa4, layout:androidx.recyclerview.widget.LinearLayoutManager@5df412a, context:net.mabako.steamgifts.activities.MainActivity@ba7ae7c
	at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:6590)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6796)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4591)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:4016)
	at android.view.View.measure(View.java:26905)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26905)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onMeasure(SwipeRefreshLayout.java:641)
	at android.view.View.measure(View.java:26905)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:26905)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26905)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:833)
	at android.view.View.measure(View.java:26905)
	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1156)
	at android.view.View.measure(View.java:26905)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
	at android.view.View.measure(View.java:26905)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26905)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26905)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26905)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:840)
	at android.view.View.measure(View.java:26905)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4281)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2946)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3229)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2651)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9819)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1429)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1437)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1046)
	at android.view.Choreographer.doFrame(Choreographer.java:936)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1405)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8324)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:581)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

**Comment by xXxPsymanxXx** [comment]
Thanks for the quick update. Unfortunately, the BUG is still present even after a clean reinstallation to beta 2 😔. I have submitted another log from beta 2.

java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionEmptyViewHolder{f290a27 position=8 id=-1, oldPos=7, pLpos:7 scrap [attachedScrap] tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{5855e46 VFED..... ......ID 0,0-720,475 #7f09014b app:id/list}, adapter:net.mabako.steamgifts.adapters.GiveawayAdapter@a443dbd, layout:androidx.recyclerview.widget.LinearLayoutManager@ca6a807, context:net.mabako.steamgifts.activities.MainActivity@ba7ae7c
	at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:6590)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6796)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4591)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:4016)
	at android.view.View.measure(View.java:26905)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26905)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onMeasure(SwipeRefreshLayout.java:641)
	at android.view.View.measure(View.java:26905)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:26905)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26905)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:833)
	at android.view.View.measure(View.java:26905)
	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1156)
	at android.view.View.measure(View.java:26905)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
	at android.view.View.measure(View.java:26905)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26905)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26905)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26905)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:840)
	at android.view.View.measure(View.java:26905)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4281)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2946)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3229)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2651)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9819)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1429)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1437)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1046)
	at android.view.Choreographer.doFrame(Choreographer.java:936)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1405)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8324)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:581)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
